- name: Fallback: kill any lingering Tomcat bootstrap java processes
  become: yes
  shell: |
    pkill -f 'org.apache.catalina.startup.Bootstrap' || true
  args:
    warn: false
  ignore_errors: yes
