---
- name: Install Java
  apt:
    name: "{{ java_package }}"
    state: present
    update_cache: yes

- name: Download Tomcat tarball
  get_url:
    url: "{{ tomcat_tarball_url }}"
    dest: "/tmp/tomcat.tar.gz"
    mode: '0644'

- name: Extract Tomcat
  unarchive:
    src: "/tmp/tomcat.tar.gz"
    dest: "/opt/"
    remote_src: yes
    creates: "{{ tomcat_install_dir }}"

- name: Copy tomcat-users.xml with Manager/Admin users
  template:
    src: tomcat-users.xml.j2
    dest: "{{ tomcat_install_dir }}/conf/tomcat-users.xml"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Tomcat

- name: Ensure Python is installed
  raw: sudo apt-get update && sudo apt-get install -y python3
  become: yes

- name: Deploy WAR file
  copy:
    src: "{{ war_source_path }}"
    dest: "{{ war_dest_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Tomcat

- name: Make startup script executable
  file:
    path: "{{ tomcat_install_dir }}/bin/startup.sh"
    mode: '0755'

- name: Start Tomcat
  shell: nohup {{ tomcat_install_dir }}/bin/startup.sh &
  args:
    executable: /bin/bash
