---
- name: Restart Tomcat
  become: yes
  shell: |
    set -eux
    {{ tomcat_install_dir }}/bin/shutdown.sh || true
    sleep 3
    {{ tomcat_install_dir }}/bin/startup.sh
  args:
    executable: /bin/bash
